#+TITLE: cs546 hw5 CUDA Programming on Comet
#+AUTHOR: Christopher Hannon
#+EMAIL: channon@iit.edu 
#+OPTIONS: H:2 num:nil toc:nil \n:nil @:t ::t |:t ^:{} _:{} *:t TeX:t LaTeX:t
#+STARTUP: showall
#+LANGUAGE:  en
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+INFOJS_OPT: view:showall toc:t ltoc:t mouse:underline path:http://orgmode.org/org-info.js
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/notebook.css" />

* How to install
./setup.sh 

The setup file compiles, and queues the sequential and cuda versions.

* Usage
Change the Size of N by modifying SCREENX and SCREENY in the defines of GoLS.c and GoLCuda.cu

* Algorithms
The algorithm is actually quite simple, we initialize a random array of NxM integer values. 
 The 2D world is stored in a 1D Array of size (sizeof(integer)*N*M). The next step is to iterated through the world and update the values.
 The new values should not overwrite the origional array until the whole world is traversed. 
 The parallel version splits the world into blocks and uses data parallelism to speed up.


Empirical data from Comet on XSEDE using sequential and CUDA 7.0 shows Execution time of:
| N              | 100     | 1000    | 10000   | 25000 |
|----------------+---------+---------+---------+-------|
| Serial Version | 0.539 s | 60.46 s | --- s   | --- s |
| Cuda Version   | 0.036 s | 0.986 s | 73.86 s | --- s |


Empirical data from Comet on XSEDE using sequential and CUDA 7.0 shows Execution time per frame of:
| N              | 100       | 1000     | 10000    | 25000  |
|----------------+-----------+----------+----------+-------|
| Serial Version | 0.00061 s | 0.068 s  | --- s    | --- s |
| Cuda Version   | 0.00004 s | 0.0012 s | 0.0845 s | --- s |

Here we can see that the serial version is capped at 1000 due to execution time (greater than 1 hour) and the Cuda version vastly outperforms the serial version.

* Screenshots
  Screen shots can be found in ./results/* where the directory names are the sizes of N.

* Reference
  -  https://stackoverflow.com/questions/459691/best-timing-method-in-c
  -  https://devtalk.nvidia.com/default/topic/453819/cuda-programming-and-performance/the-game-of-life-in-cuda/2
  -  https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life


